# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63a6a1df066d654721729ed281846bbddddc7abe1a8e53d00a5d42f1b2b494d101c37c74daff55dc0df3137d6a1f97d498f54a04e3b3e8aabcda31372752e11c

test:
  secret_key_base: a2fe8d4ef5659f372c4495129c511f7d933d3630114ed6ffd2903a90d4cbf69aa4a72d90c6a864135962dd51a5602db207e012038ccc2ce98f09545b4b1ce824

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
